name: Tmate Debug Session (India Optimized + storage)

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/share/swift
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h  # Show how much space you freed

      - name: Setup Tmate Session
        uses: mxschmitt/action-tmate@v3
        with:
          tmate-server-host: "sg1.tmate.io"
          limit-access-to-actor: true
